---
- name: Install NTP
  yum: name=ntp state=present

- name: Setup Local NTP server
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify:
         - restart ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=started enabled=yes