---
################## Disable firewall, selinux, set and add hostname
- hosts: all
  sudo: yes
  roles:
    - {role: common}

################### Config NTP
- hosts: ntp_config_server
  sudo: yes
  roles:
    - {role: ntp}

- hosts: ntp_client
  sudo: yes
  roles:
    - {role: ntp-client}

################### Update repository
- hosts: all
  sudo: yes
  roles:
    - {role: hdp}

######## Install Java
- hosts: all
  sudo: yes
  roles:
    - {role: java}

##################### Install Nagios
# role for nagios clients via NRPE
#- hosts: all
#  sudo: yes
#  roles:
#    - {role: nagios-client}

# role for nagios server
#- hosts: server
#  sudo: yes
#  roles:
#    - {role: nagios}


######## Reboot host
#- hosts: all
#  sudo: yes
#  roles:
#    - {role: reboot}


