---
################## Disable firewall, selinux, set and add hostname
- hosts: all
  roles:
    - {role: common}

################### Config NTP
- hosts: ntp_config_server
  roles:
    - {role: ntp}

- hosts: all
  roles:
    - {role: ntp-client}

################### Update repository
- host: all
  roles:
    - {role: hdp}

######## Install Java
- hosts: all
  roles:
    - {role: java}

##################### Install Nagios
# role for nagios clients via NRPE
#- hosts: all
#  sudo: yes
#  roles:
#    - {role: nagios-client}

# role for nagios server
#- hosts: server
#  sudo: yes
#  roles:
#    - {role: nagios}


######## Reboot host
#- hosts: all
#  roles:
#    - {role: reboot}


