---
- name: Copy jdk
  copy: src=jdk.tgz dest=/tmp
  
- name: Extract jdk to /usr/share/
  unarchive: src=/tmp/jdk.tgz dest=/usr/share/ remote_src=True

- name: Set java environment
  copy: src=java.sh dest=/etc/profile.d/java.sh mode=0755

- name: Reboot server
  command: /sbin/reboot

- name: Wait for the server to finish rebooting
  sudo: no
  local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300