---
- name: Install NTP
  yum: name=ntp state=present

- name: Setup Local NTP server
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
         - restart ntp

- name: Diable chronyd
  service: name=chronyd enabled=no

- name: Enable ntp
  systemd: state=started name=ntpd


- name: Be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes